# Generated by Django 5.1.1 on 2024-10-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='image',
            field=models.ImageField(default='portfolio/images/IMG1.jpeg', upload_to='experiencias/images/'),
        ),
    ]
